system:
  _target_: aspera.prompting.system_turn_templates.query_annotation_with_program_structure_guidelines
  _partial_: true
annotation_request:
  _target_: aspera.prompting.user_turn_templates.annotation_start_turn
  _partial_: true
user_program_edit_feedback:
  _target_: aspera.prompting.user_turn_templates.annotation_edit_feedback
  _partial_: true
user_environment_setup_request:
  _target_: aspera.prompting.user_turn_templates.entity_generation_followup_prompt
  _partial_: true
user_evaluation_code_generation:
  _target_: aspera.prompting.user_turn_templates.eval_function_followup_prompt
  _partial_: true
